project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Hansen"
  page-footer:
    left: "hansenx@upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/Hansen_Xie.jpg"
    pinned: true
    align: center
    title: "Hansen Xie"
    tools:
      - icon: globe
        href: https://www.linkedin.com/in/hansen-xie-58a1942a8/
        text: "Linkedin"
      - icon: github
        href: https://github.com/MUSA-550-Fall-2024/
        text: "MUSA 550 GitHub"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Background
      - href: ExploratoryAnalysisUberTrips.qmd
        text: Exploratory Analysis of Uber Trips in NYC
      - href: Cluster.qmd
        text: Weekday vs. Weekend Travel Patterns
      - href: prediction.qmd
        text: Random Forest-Based Uber Trips Prediction
        toc: true
        css: styles.css


format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
